config/routes.rb
Rails.application.routes.draw do
  
  
  resources :collections do
    resources :elements
  end
  get '/elements/delete'
  root 'pages#show'
  
  devise_for :users

  

end

app/models/collection.rb
class Collection < ActiveRecord::Base
  belongs_to :user
  has_many :elements
  
  
end

app/models/element.rb
class Element < ActiveRecord::Base
  belongs_to :collection
  
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  
  has_many :collections
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

end

app/controllers/collections_controller.rb
class CollectionsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_collection , only: [:show, :edit, :update, :destroy, :returnID]
  
  def new
    @collection = Collection.new 
  end

  def show
    
    if current_user.id != @collection.user_id
      flash.now[:alert] = "*** Cannot Edit Others Collections ***"
    end
    @elements = Element.all
  end

  def index 
    @all_collections = current_user.collections
  end 
  
  def edit
  end

  def create
    @collection = current_user.collections.new(collection_params)
    @collection.save
    redirect_to collections_path
  end
  
  def update
    @collection.update(collection_params)
    redirect_to collections_path
  end
  
  def destroy
    @collection.destroy
    redirect_to collections_path
  end

  def returnID
    @coll_id = @collection
  end
  
  private
    def set_collection
     
        @collection = Collection.find(params[:id])
      
    end
  
    def collection_params
      params.require(:collection).permit(:user_id,:object ,:name, :personal,:description)
    end
    
  
end

app/controllers/elements_controller.rb
class ElementsController < ApplicationController
  before_action :set_element, only: [:show, :edit, :update, :destroy]
  
  def index
  end

  def show
    @collection = Collection.find(params[:collection_id])
  end
  
  def create
    @element = Element.new(element_params)
    @element.collection_id = params[:collection_id]
    @element.save
    @colhelp = Collection.find(@element.collection_id)
    redirect_to collection_element_path(@colhelp , @element.id)
  end
  
  
  
  def edit
    @collection = Collection.find(params[:collection_id])
  end

  def new

    #throw params
    
    @col = Collection.find(params[:collection_id])
    @element = Element.new
    @element.collection_id = params[:collection_id]
    
  end

  def destroy
    @id = @element.collection_id
    @element.destroy
    redirect_to collections_path(@id)
  end
  
  def update
    @element.update(element_params)
    redirect_to collection_path(@element.collection_id)
  end
  
end
  private
    def element_params
      params.require(:element).permit(:collection_id,:name )
    end

   def set_element  
      @element = Element.find(params[:id])  
   end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  
  
  def show
    @collections = Collection.all
    if current_user
      @user_col = current_user.collections
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/collections_helper.rb
module CollectionsHelper
end

app/helpers/elements_helper.rb
module ElementsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/collections/_form.html.erb
  <div class="col-md-4">
<%= form_for @collection do |f| %>
<%= f.label "Collection Name" %>
<%= f.text_field :name%>
<br>
<%= f.radio_button(:personal, true) %>
<%= f.label(:personal_true, "Personal: Only you can see") %>
<br>
<%= f.radio_button(:personal, false) %>
<%= f.label(:personal_false, "Public: Everyone can see") %>
<br>
<%= f.label "Description" %>
<br>
<%= f.text_area :description, rows: 5%>

<br>
<%= f.submit %>
<!--%= link_to "Delete", collection_path(@collection), method: :delete % -->

<% end %>
  </div>
  <div class="col-md-8">&nbsp;</div>

app/views/collections/edit.html.erb
<h1>Collections#edit</h1>
<p>Find me in app/views/collections/edit.html.erb</p>

<%= render 'form' %>

<%= button_to "Delete", collection_path(@collection), method: :delete %>

app/views/collections/index.html.erb
<div class="row">
  <div class="col-md-12 text-center">
    <h1>My Collections</h1>
  </div>
</div>
<div class="row">
  <div class="col-md-4">&nbsp;</div>
  <div class="col-md-4">
<%= link_to "New" , new_collection_path %>
<br><br>
<table>
  <tr>
    <th>Collection</th>
    <th>Type</th>
  <tr/>
<% @all_collections.each do |collection| %>
 <tr>
   <td><%= link_to collection.name , collection_path(collection) %></td>
   <td> <% if (collection.personal == true) and current_user %> 
        Personal
  <% else %>
        Public
  <% end %>
   </td>
  </tr>
<% end %>
   
</table>
  </div>
  <div class="col-md-4">&nbsp;</div>
</div>

app/views/collections/new.html.erb
<div class="row">
<%= render 'form' %>
</div>

app/views/collections/show.html.erb
<div class="row">
<div class="col-md-4">
<% if current_user.id == @collection.user_id %>
  <%= link_to @collection.name, edit_collection_path(@collection)%> 

  <h3>Description</h3>
  <p><%= @collection.description %></p>

<% else %>
  <h2><%= flash[:alert] %></h2>  
<% end %>
</div>

<div class="col-md-4">
  <h3>Elements</h3>
    <% Element.all.each do |element| %>
      <% if element.collection_id == @collection.id %>
        <li> <%= link_to element.name, edit_collection_element_path(element, :collection_id => @collection.id) %></li>
      <% end %>
    <% end %>
</div>
<div class="col-md-4">
<%= link_to "Add Element", new_collection_element_path(@collection.id) %>
<br>
<br>
<%= link_to "Back to My Collections" , collections_path %>
  </div>
</div>

app/views/elements/_form.html.erb
<%= form_for new_collection_element_path(@newElement, {:collection_id => @newElement.collection_id})  do |f| %>

<%= f.label "Element Name" %>
<%= f.text_field :name %>
<!-- % :collection_id = @element.collection_id % -->
<!--  %= f.inspect % -->
<br>


<br>
<%= f.submit %>

<% end %> 

app/views/elements/delete.html.erb
<h1>Elements#delete</h1>
<p>Find me in app/views/elements/delete.html.erb</p>

app/views/elements/edit.html.erb
<div class="row">
  <div class="col-md-4">
  <p><B>Collection:</B> <%= Collection.find(@element.collection_id).name%></p>

<%= form_for [@collection, @element] do |f| %>

<%= f.label "Element Name" %>
<%= f.text_field :name %>
<!-- % :collection_id = @element.collection_id % -->
<!--  %= f.inspect % -->
<br>


<br>
<%= f.submit %>

<% end %> 

<%= button_to "Delete Element", collection_element_path(@collection, @element) , method: :delete %>
<br>
<br>
<%= link_to "Back to Collection", collection_path(@collection) %>
  </div><div class="col-md-8"></div>
</div>

app/views/elements/index.html.erb
<h1>Elements#index</h1>
<p>Find me in app/views/elements/index.html.erb</p>

app/views/elements/new.html.erb
<div class="row">
  <div class="col-md-4">
    <p>Collection <%= @col.id %> <%= @col.name %> </p>

<%= form_for [@col, @element] , action: :create do |f| %>

<%= f.label "Element Name" %>
<%= f.text_field :name, autofocus: true %>
<!-- % :collection_id = @element.collection_id % -->
<!--  %= f.inspect % -->
<br>


<br>
<%= f.submit %>

<% end %> 
  </div>
  <div class="col-md-8">&nbsp;</div>
</div>

app/views/elements/show.html.erb
<div class="row">
  <div class="col-md-4">
  <B>Element</B> <I><%= link_to @element.name, edit_collection_element_path(@collection,@element)  %></I> belongs to <B>Collection </B> <I><%= Collection.find(@element.collection_id).name %></I>
<br><br>

<%= link_to "This Collection", collection_path(@element.collection_id)   %>
  </div>
  <div class="col-md-8">&nbsp;</div>
</div>

app/views/layouts/_footer.html.erb
<p>&copy;&nbsp;<%= Date.today.year %>&nbsp;Websembly, LLC</p>

app/views/layouts/_header.html.erb
<h1>I Have Collected</h1>

<nav class="navbar navbar-inverse navbar-fixed-top">
<% if current_user %>
<p>User Logged In: <%= current_user.email %> </p>
<p><%= link_to "Home" , root_path, html_options = { class: "btn btn-primary" } %>
  <%= link_to "My Collections", collections_path, html_options = { class: "btn" }  %>
  <%= link_to "Log Out", destroy_user_session_path, html_options: { class: "btn" }, method: :delete %>

</p>
<% end %>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
  <title>I Have Collected</title>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">

  <!-- Optional theme -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap-theme.min.css">

  <!-- Latest compiled and minified JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
  
<body>
  <header> <%= render "layouts/header" %> </header>
  <container>
<%= yield %>
  <footer> <%= render "layouts/footer" %> </footer>
  </container>
</body>
</html>

app/views/pages/show.html.erb
<% if !current_user %>

<%= link_to "Sign In", new_user_session_path %>
<%= link_to "Register", new_user_registration_path %>
<% end %>

<h2>All Public Collections</h2>
<% @collections.each do |col| %>
  <% if col.personal == false %>
    <li><%= col.name %></li>
  <% end %>
<% end %>

<% if current_user %>
  <h2>Personal Collections</h2>
  <% @user_col.each do |col| %>
    <% if col.personal == true %>
      <li><%= col.name %></li>
    <% end %>
  <% end %>
<% end %>
<dev>
  
  <br>
<%= link_to "About" %>
</dev>